#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。

# プロジェクト設定

[project]
id = "Karoterra.Typst"
name = "Typst for AviUtl2"
version = "0.2.1"

# 開発時の設定

[development]
aviutl2_version = "latest"

# 成果物の設定

[artifacts.English-typst-aul2]
destination = "Language/English.typst_kr.aul2"
source = "./i18n/English.typst_kr.aul2"

[artifacts.English-aul2]
enabled = false
destination = "Language/English.aul2"
source = "https://raw.githubusercontent.com/aviutl2/aviutl2_community_translation/refs/heads/main/locales/original_english.aul2"

[artifacts.English-aul2.profiles.debug]
enabled = true

[artifacts.typst_kr-aux2]
destination = "Plugin/Karoterra.Typst/typst_kr.aux2"

[artifacts.typst_kr-aux2.profiles.debug]
build = "cargo build"
source = "target/debug/typst_kr.dll"

[artifacts.typst_kr-aux2.profiles.release]
build = "cargo build --release"
source = "target/release/typst_kr.dll"

[artifacts.README-md]
destination = "Plugin/Karoterra.Typst/README.md"
source = "./README.md"

[artifacts.LICENSE-MIT]
destination = "Plugin/Karoterra.Typst/LICENSE-MIT"
source = "./LICENSE-MIT"

[artifacts.LICENSE-APACHE]
destination = "Plugin/Karoterra.Typst/LICENSE-APACHE"
source = "./LICENSE-APACHE"

[artifacts.NOTICE-html]
destination = "Plugin/Karoterra.Typst/NOTICE.html"
source = "./NOTICE.html"

# リリース設定

[release]
package_template = "./package.txt"
package_information = "{name} v{version} by karoterra"

# カタログの設定

[catalog]
id = "Karoterra.Typst"
download_repo = { owner = "karoterra", repo = "aviutl2-typst" }
