[package]
name = "aviutl2-typst"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0 OR MIT"

[lib]
name = "typst_kr"
crate-type = ["cdylib"]

[dependencies]
aviutl2 = "0.34.0"
codespan-reporting = "0.13.1"
lru = "0.18.0"
rustc-hash = "2.1.2"
typst = "=0.15.0"
typst-layout = "=0.15.0"
typst-render = "=0.15.0"
windows = { version = "0.62.2", features = ["Win32", "Win32_System_LibraryLoader"] }

[dependencies.typst-kit]
version = "=0.15.0"
features = [
    "embedded-fonts",
    "scan-fonts",
    "datetime",
    "system-packages",
    "universe-packages",
    "system-downloader",
]
